name: gh_action_2_dan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  tags:
    - "v*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Descargar
      run: wget https://download2.gluonhq.com/openjfx/21.0.10/openjfx-21.0.10_linux-x64_bin-sdk.zip
    - name: Descompresión SDK
      run: unzip openjfx-21.0.10_linux-x64_bin-sdk.zip -d javafx-sdk
    - name: Compilar código
      run: javac --module-path javafx-sdk/javafx-sdk-21.0.10/lib --add-modules javafx.controls -d build/ src/dam/optativa/HelloWorldFx.java
    - name: Crear JAR
      run: jar --create --file=build/HelloWorldFx.jar --manifest=manifest/MANIFEST.MF -C build/ .
    - name: Crear .deb
      run: jpackage --input build/ --name HelloWorldFx --main-jar HelloWorldFx.jar --main-class dam.optativa.HelloWorldFx --type deb --module-path javafx-sdk/javafx-sdk-21.0.10/lib --add-modules javafx.controls

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: HelloWorldFx-executable
        path: HelloWorldFx.deb
        #path: HelloWorldFx.exe

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type=='tag'
      with:
        files: "*.deb"
        #files: "*.exe"
